version: '3'
services:
  tomcat:
    image: tomcat:latest
    volumes:
      - /Users/liadhazoot/hit/devops/finalProject:/usr/local/tomcat/webapps
    ports:
      - 8082:8080
  jenkins:
    image: jenkins/jenkins
    volumes:
      - /Users/liadhazoot/hit/devops/jenkins:/var/jenkins_home
      - /Users/liadhazoot/hit/devops/finalProject:/home/webapps
    ports:
      - 8081:8080
      - 50000:50000